# Load from python
FROM python
# Copy all files
RUN mkdir /data
COPY data/ /data
COPY scripts/ .
# Run requirements to install packages
RUN pip install --no-cache-dir -r requirements.txt
# When you run, run app.py
CMD ["python3", "app.py"]